name: autofix.ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

env:
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          rustflags: ""

      - name: Format Rust
        run: cargo fmt --all

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
